export interface Artist {
  id: string;
  name: string;
  category: string;
  priceRange: string;
  location: string;
  bio?: string;
  languages?: string[];
  imageUrl?: string;
}

// src/lib/data.ts
export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "John Doe",
    category: "Singer",
    location: "New York",
    priceRange: "$500 - $1000",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "2",
    name: "Jane Smith",
    category: "Dancer",
    location: "Los Angeles",
    priceRange: "$600 - $1200",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "3",
    name: "Alex Johnson",
    category: "Speaker",
    location: "Chicago",
    priceRange: "$300 - $800",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "4",
    name: "Mike Brown",
    category: "Musician",
    location: "Seattle",
    priceRange: "$700 - $1300",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "5",
    name: "Sarah Lee",
    category: "Actor",
    location: "Boston",
    priceRange: "$400 - $900",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "6",
    name: "Tom Wilson",
    category: "Comedian",
    location: "Denver",
    priceRange: "$350 - $850",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "7",
    name: "Emma Davis",
    category: "Magician",
    location: "Austin",
    priceRange: "$450 - $1000",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "8",
    name: "Robert Taylor",
    category: "Singer",
    location: "Miami",
    priceRange: "$550 - $1100",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "9",
    name: "Lisa Anderson",
    category: "Dancer",
    location: "San Francisco",
    priceRange: "$650 - $1250",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "10",
    name: "Chris Evans",
    category: "Speaker",
    location: "Houston",
    priceRange: "$320 - $850",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "11",
    name: "Kelly White",
    category: "Musician",
    location: "Portland",
    priceRange: "$750 - $1400",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "12",
    name: "David Miller",
    category: "Actor",
    location: "Atlanta",
    priceRange: "$450 - $950",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "13",
    name: "Jenny Brown",
    category: "Comedian",
    location: "Phoenix",
    priceRange: "$400 - $900",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "14",
    name: "Mark Davis",
    category: "Magician",
    location: "Dallas",
    priceRange: "$500 - $1050",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "15",
    name: "Anna Wilson",
    category: "Singer",
    location: "Philadelphia",
    priceRange: "$600 - $1150",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "16",
    name: "Paul Green",
    category: "Dancer",
    location: "San Diego",
    priceRange: "$700 - $1300",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "17",
    name: "Laura Clark",
    category: "Speaker",
    location: "Minneapolis",
    priceRange: "$350 - $900",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "18",
    name: "James Lee",
    category: "Musician",
    location: "Orlando",
    priceRange: "$800 - $1450",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "19",
    name: "Sophie Turner",
    category: "Actor",
    location: "Charlotte",
    priceRange: "$500 - $1000",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "20",
    name: "Brian Adams",
    category: "Comedian",
    location: "Las Vegas",
    priceRange: "$420 - $950",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "21",
    name: "Rachel Scott",
    category: "Magician",
    location: "Seattle",
    priceRange: "$480 - $1100",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "22",
    name: "Michael King",
    category: "Singer",
    location: "New Orleans",
    priceRange: "$580 - $1200",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "23",
    name: "Emily Harris",
    category: "Dancer",
    location: "Nashville",
    priceRange: "$680 - $1350",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "24",
    name: "Daniel Young",
    category: "Speaker",
    location: "Raleigh",
    priceRange: "$330 - $870",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "25",
    name: "Olivia Moore",
    category: "Musician",
    location: "Tampa",
    priceRange: "$780 - $1420",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "26",
    name: "Ethan Parker",
    category: "Actor",
    location: "Columbus",
    priceRange: "$470 - $980",
    imageUrl: "/placeholder.jpg",
  },
  {
    id: "27",
    name: "Nina Cox",
    category: "Comedian",
    location: "Salt Lake City",
    priceRange: "$410 - $920",
    imageUrl: "/placeholder.jpg",
  },
];